import { readable } from "svelte/store";

const workHistoryData = [
  {
    name: "Shoshana Technologies",
    title: "Software Engineer",
    tech: [
      "Smalltalk",
      "SUnit",
      "JQuery",
      "Javascript",
      "html",
      "CSS",
      "Object Oriented Programming",
    ],
    positions: [
      {
        title: "Software Engineer",
        start: "September 2013",
        end: "August 2014",
      },
    ],
  },
  {
    name: "Menlo Innovations",
    title: "Software Engineer",
    tech: [
      "Java",
      "Junit",
      "Javascript",
      "AngularJS",
      "Typescript",
      "C#",
      "Ruby",
      "Ruby on Rails",
      "Swift",
      "OpenCV",
      "Heroku",
      "NodeJS",
      "Python",
      "Postgres SQL",
      "SQLite",
      "Bootstrap",
      "html",
      "CSS",
      "SVN",
      "Git",
      "microservices",
      "CICD",
      "Linux",
      "Windows",
    ],
    positions: [
      {
        title: "Associate Software Engineer",
        start: "2014-02-07T00:00:00.000Z",
        end: "2021-02-07T02:27:50.816Z",
      },
      {
        title: "Senior Software Engineer / Agile Consultant",
        start: "",
        end: "",
      },
    ],
  },
  {
    name: "Ford Smart Mobility",
    tech: [
      "React JS",
      "Redux",
      "Java",
      "Springboot",
      "React Native",
      "Swift",
      "PCF",
      "Azure",
      "Swagger",
      "MS SQL",
      "H2 Database Engine",
      "Rabbit MQ",
      "Jenkins",
      "App Center",
      "html",
      "CSS",
      "Git",
      "microservices",
      "CICD",
      "SonarQube",
      "Linux",
      "Windows",
      "MacOS",
    ],
    positions: [
      {
        title: "Software Engineer",
        start: "Jan 2019",
        end: "",
      },
      {
        title: "Software Engineer, Team Anchor",
        start: "Jan 2019",
        end: "",
      },
    ],
  },
  {
    name: "Ford Autnonomous Vehicle (AV) LLC",
    tech: [
      "React JS",
      "Java",
      "Springboot",
      "Swift",
      "AWS Lambda",
      "AWS DynamoDB",
      "Swagger",
      "Typescript",
      "Jenkins",
      "Material-UI",
      "html",
      "CSS",
      "Git",
      "microservices",
      "CICD",
      "SonarQube",
      "Linux",
      "Windows",
      "MacOS",
    ],
    positions: [
      {
        title: "Software Engineer, Team Anchor",
        start: "Jan 2019",
        end: "",
      },
      {
        title: "Software Engineer, Product Line Anchor",
        start: "Jan 2019",
        end: "",
      },
    ],
  },
];

export const workHistory = readable(workHistoryData);
